import os
import io
import re
import base64
from docx import Document
from docx.shared import Inches
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
import openpyxl
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as ReportLabImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class ExportService:

    COLOR_PRIMARY = RGBColor(27, 54, 93)     # Deep Navy
    COLOR_ACCENT = RGBColor(108, 92, 231)    # Sasha Accent Purple
    COLOR_TEXT_DARK = RGBColor(45, 52, 54)   # Slate Text

    @staticmethod
    def _decode_image(b64_str: str) -> io.BytesIO:
        if not b64_str:
            return None
        if ',' in b64_str:
            b64_str = b64_str.split(',')[1]
        img_bytes = base64.b64decode(b64_str)
        return io.BytesIO(img_bytes)

    @staticmethod
    def _add_pptx_header(slide, title_text: str):
        tx_box = slide.shapes.add_textbox(PptxInches(0.8), PptxInches(0.4), PptxInches(11.7), PptxInches(0.8))
        tf = tx_box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = title_text
        p.font.size = Pt(24)
        p.font.bold = True
        p.font.color.rgb = ExportService.COLOR_PRIMARY

    @staticmethod
    def generate_word(title: str, insights: list, table_data_list: list = None, chart_images_b64: list = None) -> io.BytesIO:
        doc = Document()
        doc.add_heading(title or "Executive Analytical Report", level=0)
        
        if insights:
            doc.add_heading("Key Findings & Recommendations", level=1)
            for insight in insights:
                doc.add_paragraph(insight, style='List Bullet')
            
        if chart_images_b64:
            doc.add_heading("Visualizations & Diagrams", level=1)
            for idx, img_b64 in enumerate(chart_images_b64, 1):
                img_stream = ExportService._decode_image(img_b64)
                if img_stream:
                    doc.add_paragraph(f"Figure {idx}: Visual Analysis", style='Caption')
                    doc.add_picture(img_stream, width=Inches(6.0))

        if table_data_list:
            doc.add_heading("Data Summaries & Tables", level=1)
            for tdata in table_data_list:
                if isinstance(tdata, dict) and "headers" in tdata and "rows" in tdata:
                    doc.add_heading(tdata.get("title", "Data Table"), level=2)
                    headers = tdata["headers"]
                    rows = tdata["rows"]
                    
                    table = doc.add_table(rows=1, cols=len(headers))
                    table.style = 'Table Grid'
                    hdr_cells = table.rows[0].cells
                    for i, header in enumerate(headers):
                        hdr_cells[i].text = str(header)
                        
                    for row in rows:
                        row_cells = table.add_row().cells
                        for i, val in enumerate(row):
                            row_cells[i].text = str(val)
                    doc.add_paragraph("")
                    
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream

    @staticmethod
    def generate_pptx(title: str, insights: list, table_data_list: list = None, chart_images_b64: list = None) -> io.BytesIO:
        prs = Presentation()
        prs.slide_width = PptxInches(13.333)
        prs.slide_height = PptxInches(7.5)
        blank_layout = prs.slide_layouts[6]

        # Slide 1: Title
        slide1 = prs.slides.add_slide(blank_layout)
        accent_bar = slide1.shapes.add_shape(MSO_SHAPE.RECTANGLE, PptxInches(0), PptxInches(0), PptxInches(0.4), PptxInches(7.5))
        accent_bar.fill.solid()
        accent_bar.fill.fore_color.rgb = ExportService.COLOR_ACCENT
        accent_bar.line.fill.background()

        title_box = slide1.shapes.add_textbox(PptxInches(1.2), PptxInches(2.5), PptxInches(11), PptxInches(2))
        tf1 = title_box.text_frame
        tf1.word_wrap = True
        p1 = tf1.paragraphs[0]
        p1.text = title or "Executive Analysis Report"
        p1.font.size = Pt(36)
        p1.font.bold = True
        p1.font.color.rgb = ExportService.COLOR_PRIMARY

        p2 = tf1.add_paragraph()
        p2.text = "Generated by Sasha AI • Visual & Data Intelligence"
        p2.font.size = Pt(16)
        p2.font.color.rgb = ExportService.COLOR_TEXT_DARK
        p2.space_before = Pt(12)

        # Slide 2: Insights
        if insights:
            slide2 = prs.slides.add_slide(blank_layout)
            ExportService._add_pptx_header(slide2, "Executive Summary & Findings")

            content_box = slide2.shapes.add_textbox(PptxInches(0.8), PptxInches(1.4), PptxInches(11.7), PptxInches(5.4))
            tf2 = content_box.text_frame
            tf2.word_wrap = True

            for idx, insight in enumerate(insights):
                p = tf2.paragraphs[0] if idx == 0 else tf2.add_paragraph()
                p.text = f"•  {insight}"
                p.font.size = Pt(15)
                p.font.color.rgb = ExportService.COLOR_TEXT_DARK
                p.space_after = Pt(8)

        # Dynamic Slides: Charts and Mermaid Diagrams (Proportional Centered Placement)
        if chart_images_b64:
            for idx, img_b64 in enumerate(chart_images_b64, 1):
                img_stream = ExportService._decode_image(img_b64)
                if img_stream:
                    chart_slide = prs.slides.add_slide(blank_layout)
                    ExportService._add_pptx_header(chart_slide, f"Visual Analysis ({idx}/{len(chart_images_b64)})")
                    
                    chart_slide.shapes.add_picture(
                        img_stream, 
                        PptxInches(1.6), PptxInches(1.4), 
                        width=PptxInches(10.1)
                    )

        # Dynamic Slides: Tables
        if table_data_list:
            for tdata in table_data_list:
                if isinstance(tdata, dict) and "headers" in tdata and "rows" in tdata:
                    table_slide = prs.slides.add_slide(blank_layout)
                    ExportService._add_pptx_header(table_slide, tdata.get("title", "Structured Data Summary"))

                    headers = tdata["headers"]
                    rows = tdata["rows"]
                    
                    num_cols = len(headers)
                    num_rows = len(rows) + 1

                    table_shape = table_slide.shapes.add_table(
                        num_rows, num_cols, 
                        PptxInches(0.8), PptxInches(1.5), PptxInches(11.7), PptxInches(min(0.4 * num_rows, 5.2))
                    )
                    table = table_shape.table

                    for c_idx, header in enumerate(headers):
                        cell = table.cell(0, c_idx)
                        cell.text = str(header)
                        cell.fill.solid()
                        cell.fill.fore_color.rgb = ExportService.COLOR_PRIMARY
                        for p in cell.text_frame.paragraphs:
                            p.font.bold = True
                            p.font.color.rgb = RGBColor(255, 255, 255)
                            p.font.size = Pt(13)

                    for r_idx, row in enumerate(rows):
                        for c_idx, val in enumerate(row):
                            cell = table.cell(r_idx + 1, c_idx)
                            cell.text = str(val)
                            for p in cell.text_frame.paragraphs:
                                p.font.size = Pt(11)
                                p.font.color.rgb = ExportService.COLOR_TEXT_DARK

        file_stream = io.BytesIO()
        prs.save(file_stream)
        file_stream.seek(0)
        return file_stream

    @staticmethod
    def generate_excel(title: str, table_data_list: list = None) -> io.BytesIO:
        wb = openpyxl.Workbook()
        wb.remove(wb.active)

        if table_data_list:
            for idx, tdata in enumerate(table_data_list, 1):
                if isinstance(tdata, dict) and "headers" in tdata and "rows" in tdata:
                    sheet_title = tdata.get("title", f"Summary_{idx}")
                    sheet_title = re.sub(r'[\\/*?:\[\]]', '', sheet_title)[:30] or f"Sheet_{idx}"
                    ws = wb.create_sheet(title=sheet_title)
                    
                    ws.append(tdata["headers"])
                    for row in tdata["rows"]:
                        ws.append(row)
        else:
            ws = wb.create_sheet(title="Summary")
            ws.append(["Information"])
            ws.append(["No structured table data provided for export."])

        file_stream = io.BytesIO()
        wb.save(file_stream)
        file_stream.seek(0)
        return file_stream

    @staticmethod
    def generate_pdf(title: str, insights: list, table_data_list: list = None, chart_images_b64: list = None) -> io.BytesIO:
        file_stream = io.BytesIO()
        doc = SimpleDocTemplate(file_stream, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, spaceAfter=12)
        story.append(Paragraph(title or "Executive Analytical Report", title_style))
        story.append(Spacer(1, 12))

        if insights:
            story.append(Paragraph("Key Findings", styles['Heading2']))
            for insight in insights:
                story.append(Paragraph(f"• {insight}", styles['Normal']))
                story.append(Spacer(1, 4))
            story.append(Spacer(1, 12))

        if chart_images_b64:
            story.append(Paragraph("Visual Data Analysis & Diagrams", styles['Heading2']))
            story.append(Spacer(1, 6))
            for img_b64 in chart_images_b64:
                img_stream = ExportService._decode_image(img_b64)
                if img_stream:
                    story.append(ReportLabImage(img_stream, width=450, height=240))
                    story.append(Spacer(1, 14))

        if table_data_list:
            for tdata in table_data_list:
                if isinstance(tdata, dict) and "headers" in tdata and "rows" in tdata:
                    story.append(Paragraph(tdata.get("title", "Data Summary"), styles['Heading2']))
                    story.append(Spacer(1, 6))

                    data = [tdata["headers"]] + tdata["rows"]
                    t = Table(data)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1b365d")),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 14))

        doc.build(story)
        file_stream.seek(0)
        return file_stream